### ISSUE TITLE
Plugin breaks when JSCS is used with plugin

### ISSUE THREAD

**Issue by RaYell** [globexdesigns/brackets-jscs#28]
I have a Brackets with JSCS plugin working fine for a while, but recently I wanted to add a plugin to my `.jscsrc` configuration (https://github.com/jscs-dev/jscs-jsdoc) but as soon as I did this I started getting errors in Brackets:

```
Unexpected JSCS processing error: Cannot find module 'jscs-jsdoc'
```

The configuration section I've added to `.jscsrc` is

```
    "plugins": [
        "jscs-jsdoc"
    ],
    "jsDoc": {
        "checkAnnotations": "jsdoc3",
        "checkParamNames": true,
        "requireParamTypes": true,
        "checkRedundantParams": true,
        "checkReturnTypes": true,
        "checkRedundantReturns": true,
        "requireReturnTypes": true,
        "checkTypes": "strictNativeCase",
        "checkRedundantAccess": true,
        "enforceExistence": "exceptExports",
        "requireNewlineAfterDescription": true,
        "requireDescriptionCompleteSentence": true,
        "requireParamDescription": true
    }
```

The `jscs-jsdoc` module is installed correctly as it works perfectly well when I run JSCS from command line.

**Comment by globexdesigns** [comment]
In order to get the plugin to work with the Brackets extension you'll need to either:

1) Install the plugin globally (ie. npm install -g your_plugin), or
2) Install the plugin inside the brackets-jscs extension directory (ie. cd ~/Your/Brackets/Extension/Dir/user/globexdesigns.brackets-jscs && npm install your_plugin)

Then restart Brackets.
