### ISSUE TITLE
How to upgrade to JSCS 2.0.0 ?

### ISSUE THREAD

**Issue by glepretre** [globexdesigns/brackets-jscs#31]
Hello,

Our team is updating our .jscsrc config files to use JSCS 2.0.0. They are using vi as code editor.
I am using brackets and your plugin but I can't manage to upgrade the JSCS version. 

I tried upgrading the jscs node module in the plugin directory and globally, unsuccessfully.

I still have an `Unsupported rule` error. Do you know how can I do?

Thanks.

**Comment by globexdesigns** [comment]
Hmm, upgrading the JSCS version inside the extension directory should do the trick. Have you tried closing and re-opening Brackets after upgrading?

**Comment by glepretre** [comment]
Nope :smile: I had just tried to reload it with <kbd>F5</kbd>.
Closing and reopening worked :wink:

Is it normal that even if your `package.json` set `"jscs": "latest"` : it is installed with `jscs@1.13.1` from the extensions registry?

**Comment by globexdesigns** [comment]
Yeah, you need to fully shut down Brackets because JSCS actually runs inside the Node.js instance and F5'ing Brackets just reloads the UI.

**Comment by hacker112** [comment]
I also have problem that brackets-jscs does install 1.13.1 instead of 2.x. If I manually delete the node_modules folder and run a npm install in the folder I get 2.1.0. BUT when I remove the brackets-jscs, even restart the computer and then reinstall the extension I get 1.13.1 installed. 

It is like it is somehow some cached value of "latest" that is used. Do you know where this weird error comes from and how it can be solved without installing it manually?

**Comment by glepretre** [comment]
@hacker112 I think that the archive provided by the registry is bundled and cached when the version gets updated :wink:

**Comment by hacker112** [comment]
@glepretre That makes sense, even though it seems like a bit of bad design ;-)

@globexdesigns Could you explicitly increase the version number of JSCS and bump the version in the Brackets Registry? :)
